# Generated by Django 2.2 on 2021-09-06 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('writer', '0002_author_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='writing',
            name='modification_date',
            field=models.DateField(null=True),
        ),
    ]
